# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"new_id": "00_util.ipynb",
         "list_partition": "00_util.ipynb",
         "write_file": "00_util.ipynb",
         "read_file": "00_util.ipynb",
         "get_notebook_name": "00_util.ipynb",
         "run_shell": "00_util.ipynb",
         "run": "00_util.ipynb",
         "node": "00_util.ipynb",
         "spiral": "00_util.ipynb"}

modules = ["util.py"]

doc_url = "https://fc1943s.github.io/tictactoe_spiral/"

git_url = "https://github.com/fc1943s/tictactoe_spiral/"

def custom_doc_links(name): return None
