# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"new_id": "00_util.ipynb",
         "list_partition": "00_util.ipynb",
         "write_file": "00_util.ipynb",
         "read_file": "00_util.ipynb",
         "get_notebook_name": "00_util.ipynb",
         "run_shell": "00_util.ipynb",
         "run": "00_util.ipynb",
         "run_node": "00_util.ipynb",
         "node": "02_ipython_magic.ipynb",
         "spiral": "02_ipython_magic.ipynb",
         "spi": "02_ipython_magic.ipynb",
         "spir": "02_ipython_magic.ipynb",
         "AppVariables": "03_tictactoe_pyteal.ipynb",
         "DefaultValues": "03_tictactoe_pyteal.ipynb",
         "AppActions": "03_tictactoe_pyteal.ipynb",
         "clear_program": "03_tictactoe_pyteal.ipynb",
         "money_refund_logic": "03_tictactoe_pyteal.ipynb",
         "game_funds_escrow": "03_tictactoe_pyteal.ipynb",
         "has_player_won": "03_tictactoe_pyteal.ipynb",
         "is_tie": "03_tictactoe_pyteal.ipynb",
         "play_action_logic": "03_tictactoe_pyteal.ipynb",
         "initialize_players_logic": "03_tictactoe_pyteal.ipynb",
         "app_initialization_logic": "03_tictactoe_pyteal.ipynb",
         "application_start": "03_tictactoe_pyteal.ipynb",
         "NetworkInteraction": "04_algo_network.ipynb",
         "get_default_suggested_params": "04_algo_network.ipynb",
         "ApplicationTransactionRepository": "04_algo_network.ipynb",
         "ASATransactionRepository": "04_algo_network.ipynb",
         "PaymentTransactionRepository": "04_algo_network.ipynb",
         "GameEngineService": "05_tictactoe_testnet.ipynb"}

modules = ["util.py",
           "ipython_magic.py",
           "tictactoe_pyteal.py",
           "algo_network.py",
           "tictactoe_testnet.py"]

doc_url = "https://fc1943s.github.io/tictactoe_spiral/docs/"

git_url = "https://github.com/fc1943s/tictactoe_spiral/"

def custom_doc_links(name): return None
