# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/02_ipython_magic.ipynb (unless otherwise specified).

__all__ = ['node', 'spiral', 'spi', 'spir']

# Cell

import sys
sys.path.append('..')
import lib_py.util as util
from IPython.core.magic import register_cell_magic

_node_cache = ''
_notebook_name = None

@register_cell_magic
def node(arg, cell, test=False):
    global _node_cache
    global _notebook_name

    ipython_node_path = '_ipython_node.ts'

    def split_imports(code): return util.list_partition(code.splitlines(), lambda line: line.startswith('import '))
    cache_imports, cache_exports = split_imports(_node_cache)
    cell_imports, cell_exports = split_imports(cell)
    cell_exports = '\n'.join(cell_exports).strip('\n').split('\n')

    if arg == 'run':
        ts_imports = cache_imports
        ipython_imports = cache_imports + cell_imports

        ts_exports = cache_exports
        ipython_exports = cache_exports \
            + ([] if cell_exports == ['']
            else (['', '// cell', 'var run = async (arg: string) => {'] + cell_exports + ['}', f'await run("{arg}")']))
    elif arg == 'export':
        ts_imports = cache_imports + cell_imports
        ipython_imports = ts_imports

        ts_exports = cache_exports + ([] if cell_exports == [''] else (['', '// cell'] + cell_exports))
        ipython_exports = ts_exports

    def join_imports(imports, exports):
        return ''.join([
            '\n'.join(list(dict.fromkeys(imports))),
            '' if len(imports) == 0 or len(exports) == 0 else '\n\n\n',
            '\n'.join(exports).strip('\n') + '\n'
        ])
    new_code_ts = join_imports(ts_imports, ts_exports)
    new_code_ipython = join_imports(ipython_imports, ipython_exports)

    def cwpath(arg): return os.path.abspath(os.path.join(os.getcwd(), '..', 'lib_ts', arg))

    util.write_file(cwpath(ipython_node_path), new_code_ipython)

    result = util.run_node(cwpath(ipython_node_path)).splitlines() if arg == 'run' else []

    _node_cache = new_code_ts

    if test:
        return result, new_code_ts, new_code_ipython
    else:
        if new_code_ts != '\n':
            if _notebook_name is None:
                _notebook_name = util.get_notebook_name()

            ts_node_path = cwpath(f'{_notebook_name}.ts')

            util.write_file(ts_node_path, new_code_ts)

            return result if arg == 'run' else ts_node_path

        return result


# Cell

import shutil
import os
import time
from IPython.core.magic import register_cell_magic

def _get_spiral_cache_empty(): return {'spi': '', 'spir': '', 'run': '', '': ''}
_spiral_cache = _get_spiral_cache_empty()

@register_cell_magic
def spiral(arg, cell, test=False):
    global _spiral_cache
    global _notebook_name

    last_spiral_cache = _spiral_cache

    args = arg.split(' ')
    def get_arg(i, d=''): return next(iter(args[i:i+1]), d)
    arg = args[0]

    def split_imports(code): return util.list_partition(code.splitlines(), lambda line: line.startswith('open '))
    cache_imports, cache_exports = split_imports(_spiral_cache[arg])

    cell_imports, cell_exports = split_imports(cell)
    cell_exports = '\n'.join(cell_exports).strip('\n').split('\n')

    if arg == 'run':
        cell_imports = ['open util', 'open console_fsx'] + cell_imports
        cell_exports = ['inl main () : () = '] + list(map(lambda l: f'    {l}', cell_exports))

    spi_imports = cache_imports + cell_imports
    spi_exports = cache_exports + ([] if cell_exports == [''] else (['', '// cell'] + cell_exports))

    def join_imports(imports, exports):
        return ''.join([
            '\n'.join(list(dict.fromkeys(imports))),
            '' if len(imports) == 0 or len(exports) == 0 else '\n\n\n',
            '\n'.join(exports).strip('\n') + '\n'
        ])
    new_code_spi = join_imports(spi_imports, spi_exports)

    if arg in ['spi', 'spir']:
        if _notebook_name is None:
            _notebook_name = util.get_notebook_name()
        spi_path = f'{_notebook_name}.{arg}'
    else:
        spi_path = f'main.spi'

    _spiral_cache[arg] = new_code_spi

    if test:
        return new_code_spi
    else:
        def cwpath(arg): return os.path.abspath(os.path.join(os.getcwd(), '..', arg))

        if new_code_spi != util.read_file(cwpath('main.spi')):
            if arg == 'run':
                shutil.copyfile(cwpath('main.spi'), cwpath('main.spi.tmp'))
                shutil.copyfile(cwpath('main.fsx'), cwpath('main.fsx.tmp'))
                shutil.copyfile(cwpath('main.py'), cwpath('main.py.tmp'))

            try:
                util.write_file(cwpath(spi_path), new_code_spi)

                if arg == 'run':
                    old_code_fsx = util.read_file(cwpath('main.fsx'))
                    new_code_fsx = old_code_fsx

                    code = '\n'.join([
                        f'import * as spiral_api from "../lib_ts/spiral_api"',
                        f'await spiral_api.spiToFsx("{cwpath("main.spi")}")'
                    ])
                    result = util.run_node(code, timeout=int(get_arg(1, 3))).splitlines()
                    print(f'build output: {result}')

                    start = time.time()
                    while old_code_fsx == new_code_fsx and time.time() - start < 5:
                        time.sleep(0.2)
                        new_code_fsx = util.read_file(cwpath('main.fsx'))

                    os.rename(cwpath('main.fsx'), cwpath('_ipython_spi.fsx'))
                    print(f'fsx: {new_code_fsx}')

            except Exception as e:
                print(f'ipython_magic.spiral() error. new_code_spi={new_code_spi}')
                _spiral_cache = last_spiral_cache
                raise e
            finally:
                if arg == 'run':
                    os.rename(cwpath('main.spi.tmp'), cwpath('main.spi'))
                    os.rename(cwpath('main.fsx.tmp'), cwpath('main.fsx'))
                    os.rename(cwpath('main.py.tmp'), cwpath('main.py'))

        return cwpath(spi_path)

@register_cell_magic
def spi(arg, cell, test=False):
    return spiral('spi', cell, test)

@register_cell_magic
def spir(arg, cell, test=False):
    return spiral('spir', cell, test)
